export const QUERY_KEY = {
  POST_LOGIN: "POST_LOGIN",
  GET_RECEIVNGS_SUMMARY: "GET_RECEIVINGS_SUMMARY",
  GET_RECEIVINGS_EXPECT: "GET_RECEIVINGS_EXPECT",
  GET_RECEIVINGS_ID_EXPECT: "GET_RECEIVINGS_ID_EXPECT",
  GET_RECEIVING_PRODUCT: "GET_RECEIVING_PRODUCT",
};
